### PR TITLE
expose pprof profiling and dynamic log-level endpoints

### PR DESCRIPTION
**Pull request by shashidharatd**
This is for the story in pivotaltracker
[#91795762]

For this latest code of cf-debug-server, cf-lager and lager is bumped in Godeps
Have also verified, and its working.

### CODE REVIEW

**Comment by tsaleh** [comment]
Thanks, @shashidharatd!  Could you surround this with tests as well?

**Comment by shashidharatd** [comment]
Hi @tsaleh,
  Have added the testcases for --debugAddr flag (pprof endpoint). plz check and let me know if the code change is ok.

**Comment by shashidharatd** [comment]
Added few more asserts to the testcase

**Comment by craigfurman** [comment]
Looks good!

Reviewed by @avade and me

**Pull request merged**
