### PR TITLE
Ensure non-nil AuthConfig and HTTPRequestFactory values

### PR DESCRIPTION
**Pull request by caseyhadden**
The version of the Docker dependency used currently requires a non-nil AuthConfig and HTTPRequestFactory in the NewSession call when TLS is used. This change provides empty, non-nil values for those items.

We submitted the corporate CLA for SAS Institute, Inc. yesterday to the contributors address at cloudfoundry.org.

This should fix both #31 and #27.

### CODE REVIEW

**Comment by goonzoid** [comment]
Thanks @caseyhadden! I seem to remember reading that you thought your organisation had signed the Corporate CLA. Were you able to confirm that in the end? If so, please can you ensure you've followed the instructions in the message from cfdreddbot above to make your membership of the appropriate Github org public? Once this is done, the PR needs to be closed and resubmitted to retrigger the bot, and then we can try to get this merged.

Please let me know if you have any problems. Thanks.

**Comment by caseyhadden** [comment]
Hi @goonzoid,

Yes, we have signed and submitted. However, we used Schedule A to list contributors instead of providing a GitHub organization. Chip Childers from the CFF contacted us to see whether we'd be willing to use the more automated, organization based method. I'm discussing that internally with the folks responsible for our GitHub organization and legal team to determine how they are comfortable setting things up. Once we get that sorted out so cfdreddbot will be happy, I can definitely close and resubmit.

Thanks.

**Comment by goonzoid** [comment]
Thanks. It may also be possible that we can confirm that you've signed some other way. I'll make some enquiries here and see if we can do that so that we can get this merged sooner.

**Comment by caseyhadden** [comment]
It looks like we will be able to use the GitHub organization identification method. We'll have to resubmit the CLA in order to do that which is not a big deal. However, the necessary folks to re-execute it on the legal side are unavailable until Monday.

I'll plan on pushing that forward here and then closing and resubmitting this pull request once we have that finalized unless I hear otherwise.

Apologies for the churn.

**Comment by caseyhadden** [comment]
We received confirmation today from CFF that our organization has been whitelisted for contribution. Closing this pull request to resubmit as requested.

**Pull request closed without merging**
