### PR TITLE
define setns() for debian systems

### PR DESCRIPTION
**Pull request by b**
define setns() for all those debian systems with new kernels and old glibc

### CODE REVIEW

**Comment by goonzoid** [comment]
Hi @b. Thanks for the PR!

We'll take a closer look at this soon, but in the mean time it's worth mentioning that we're likely to replace nstar with a Go implementation pretty soon, at which point this _may_ break again (we don't support much other than ubuntu 14.04 at the moment) for the systems you talk about. Just a heads-up!

If you're interested in keeping an eye on upcoming work, there's a public Tracker project for garden-linux [here](https://www.pivotaltracker.com/n/projects/1158420).

**Comment by b** [comment]
no worries. i hit this on raspberry pi 2/raspbian wheezy. even if we aren't
going to officially support it, might be nice to at least not break it, if
we can help it.

**Comment by goonzoid** [comment]
Sure. If it turns out that we do break it when porting to Go, I expect we'll be happy to accept a PR that fixes it again. It's just that we may not notice if we break it, as our regular testing only targets ubuntu 14.04.

**Comment by goonzoid** [comment]
I've just had a chat with the rest of the team, and the consensus is that we'd rather not "rock the boat" with nstar so close to rewriting it (which we expect to do this month), so I'm going to close this. Sorry.

**Comment by glyn** [comment]
[nstar->Go story](https://www.pivotaltracker.com/story/show/90422514) in case you want to keep an eye on it.

**Comment by b** [comment]
pretty disappointed in this response, folks.

**Comment by glyn** [comment]
Hi Benjamin

Your change causes our build to fail. Please could you adjust the PR?
```
cc -c -Wall -O0 -g -ggdb -rdynamic  nstar.c
nstar.c: In function 'main':
nstar.c:159:23: error: 'CLONE_NEWNS' undeclared (first use in this function)
   rv = setns(mntnsfd, CLONE_NEWNS);
                       ^
nstar.c:159:23: note: each undeclared identifier is reported only once for each function it appears in
nstar.c:168:18: error: 'CLONE_NEWUSER' undeclared (first use in this function)
   setns(usrnsfd, CLONE_NEWUSER);
                  ^
```

Regards,
Glyn

**Comment by goonzoid** [comment]
Looks like this fizzled out. Nstar probably isn't _that_ long for this world anyway, so I'll close.

**Pull request closed without merging**
